### ISSUE TITLE
*bug* in decoder when training is performed with *prepend_inputs_masked_attention*

### ISSUE THREAD

**Issue by nimas62** [tensorflow/tensor2tensor#680]
### Description
Problem: *CNN_dailymail*
Model: Transformer
hparams: transformer_prepend, transformer_base_v2

When I train the model with *transformer_prepend* hparams, the outputs of the decoder are a sequence of a repeated word. "foo, foo, foo, ...". I use transformer_base_v2 and set the max_lenght to 0. So the only difference between these two sets of parameters is the *prepend_inputs_masked_attention*. Without it, the outputs are as they supposed to be, but the performance of the model decreases by approximately 40%. It must be a *bug* in the *decoder*.
> …

### *TensorFlow* and *tensor2tensor* versions
TensorFlow 1.6, tensor2tensor 1.5.5

> …

### In case of bug report: Steps to reproduce the problem

> …

### In case of bug report: Error log

> …

**Comment by ozeron** [comment]
Hello, 
Confirm same issue with repeated words in `transformer_prepend` hparams.

**Comment by nimas62** [comment]
It's all about hyperparameters. So there's no need to include your command. transformer_prepend and transformer_base sets both have the same origin which is transformer_base_v2. You can check all the hparams in tensor2tensor/models/transformer.py The difference is max_length=0 and prepend_inputs_masked_attention in transformer_prepend. I checked the max_length of zero, it's ok. the problem lies in the masked attention.

**Comment by gaceladri** [comment]
@nimas62 I tried to decode from my current model trained with `batch_size = 1536` `learning_rate=0.2` and for 75002 steps.
(some metrics are bugged, for example in this example rouge 2 is just until the step 42k meanwhile the top5 acc is to the step 75k

![screenshot from 2018-03-31 15-22-27](https://user-images.githubusercontent.com/7850682/38164134-94d1d652-34f7-11e8-885c-e0dc77eb764b.png)

I tried to decode from my model, the steps that I followed was: copy one article in a .txt inside the t2t_data named "newsum.txt" and an empty file inside the same folder named "summarization.txt"

the command that I ran:

`t2t-decoder --data_dir=~/t2t_data --problems=summarize_cnn_dailymail32k --model=transformer --hparams_set=transformer_prepend --output_dir=~/t2t_train/sum2 --decode_hparams="beam_size=4,alpha=0.6" --decode_from_file=/home/proto/t2t_data/newsum.txt --decode_to_file=/home/proto/t2t_data/summarization.txt`

the input:

> WASHINGTON — Congressional Republicans have a new fear when it comes to their    health care lawsuit against the Obama administration: They might win. The incoming Trump administration could choose to no longer defend the executive branch against the suit, which challenges the administration’s authority to spend billions of dollars on health insurance subsidies for and Americans, handing House Republicans a big {...}

the output was:

> INFO:tensorflow:Inference results OUTPUT:                                                                                                               . . . . . . . . . . . . . . . . . . . . . . . . . .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . £ . £ £ £ £ £ £ £ £ £ . £ . £ . £ . £ . £ . £ £ £ £ £ £ £ £ . £ . £ £ £ £ £ £ £ . £ . £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £
[2018-03-31 15:11:38,501] Inference results OUTPUT:                                                                                                               . . . . . . . . . . . . . . . . . . . . . . . . . .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . £ . £ £ £ £ £ £ £ £ £ . £ . £ . £ . £ . £ . £ £ £ £ £ £ £ £ . £ . £ £ £ £ £ £ £ . £ . £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £ £
INFO:tensorflow:Inference results INPUT: 
[2018-03-31 15:11:38,501] Inference results INPUT: 
INFO:tensorflow:Inference results OUTPUT:   . . . . . . . . . . . . . . . . .     . . . . . . .     . . . . . . . . . . . . . . . . . . .   . . . . . . . . . . . .  . . . . . . . .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .  .  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
[2018-03-31 15:11:38,506] Inference results OUTPUT:   . . . . . . . . . . . . . . . . .     . . . . . . .     . . . . . . . . . . . . . . . . . . .   . . . . . . . . . . . .  . . . . . . . .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .  .  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .

I suppose that I did something wrong.
I will check what happened, but meanwhile... this is my result.

**Comment by gaceladri** [comment]
Results of the model after 17k steps. I know are few steps but the results does not seems promising.

![screenshot from 2018-03-31 22-23-36](https://user-images.githubusercontent.com/7850682/38167757-3457956e-3533-11e8-9b67-997193f22ddc.png)

It would be good if anyone could share a good pre-trained model.

**Comment by nimas62** [comment]
What I got isn't better than this. This model doesn't work well. In the quick start guide, they have said "We suggest to use --model=transformer and --hparams_set=transformer_prepend for this task. This yields good ROUGE scores." I wish someone add more details so that we could replicate the experiment.
Tuning model needs time and patience. But When you can't rely on the model, you don't know whether you have to tune it better or it's a bug(s), and it's really confusing.

**Comment by nimas62** [comment]
Which python-tensorflow matches are you using? I had python 2.7 (and used tensorflow for python 2.7 of course). I should try python 3.5.

**Comment by gaceladri** [comment]
I am using tf 1.7rc and python 3.5. By the way, I have found other repo that you could check for summarization, https://github.com/abisee/pointer-generator. I have found that the state-of-the-art is not very promising about abstractive summarization that was that I was looking for, so you can check this repo and see if it is helpful to you. @nimas62 . Happy coding.

**Comment by rsepassi** [comment]
This was indeed a bug that should now be fixed.

**Comment by lzzk** [comment]
i still have the same problem. I am using tensorflow 1.10 , tensor2tensor 1.9 and python 3.6.

**Comment by colmantse** [comment]
same, a lot of repetition of sentences that make no sense.

**Comment by kaihoang** [comment]
I also trained transformer for summarization. I'm using tensorflow 1.09, tensor2tensor 1.9, python 3.52. I used hparams=transformer_prepend and model=transformer for training. Due to memory constraint, I used batch_size=256 and trained the model for around 160k training steps. I check how well the model is doing by create a new .txt file that contains an article from CNN and use t2t-decoder to generate summary. My command is as follow:

'''
t2t-decoder --data_dir=$DATA_DIR --problem=$PROBLEM --model=$MODEL --hparams_set=$HPARAMS --output_dir=$TRAIN_DIR --decode_hparams="beam_size=$BEAM_SIZE,alpha=$ALPHA" --decode_from_file=$DECODE_FILE --decode_to_file=summarization.txt 
'''

**Comment by kaihoang** [comment]
Here is the details of the training: 

![image](https://user-images.githubusercontent.com/36524350/47238882-a4103d80-d3b1-11e8-996c-11f188a4107c.png)

![image](https://user-images.githubusercontent.com/36524350/47238902-aecad280-d3b1-11e8-828f-719c53aaf31d.png)

**Comment by mehmedes** [comment]
@hoang-ho, @gacelardi: you mentioned that you decreased the ```batch_size``` in order to fit the model onto your gpu. Please note that in transformer prepend ```max_length``` is set to zero, which means that ```max_length = batch_size```. By decreasing ```batch_size``` the model may not be trained on the necessary data length. The excerpts from tensorboard and the loss results stated above look like the model is diverging, which may be due to the decreased ```batch_size```. You may decrease the ```learning_rate``` to counteract divergence but that may not be sufficient as the ```max_length``` may still be too low due to the decreased ```batch_size```.
Have you tried setting ```max_length``` to a certain number while decreasing ```batch_size```?
You may also try ```transformer_moe```, which will allow you to train models with greater batch sizes without the need of more computation.

**Comment by mehmedes** [comment]
Making sure batch size is 4096 when max length= 0 really helps!
```
PROBLEM=summarize_cnn_dailymail32k                                        
MODEL=transformer                                                         
HPARAMS=transformer_tpu                                                   
                                                     
                                                                                                                                              
t2t-trainer\                                                              
  --data_dir=$DATA_DIR \                                                  
  --problem=$PROBLEM \                                                    
  --worker_gpu=4 \                                                        
  --hparams="batch_size=4096, max_length=0"
```

```INFO:tensorflow:Finished evaluation at 2019-01-16-21:37:36
INFO:tensorflow:Saving dict for global step 2052000: global_step = 2052000, loss = 2.6060317, metrics-summarize_cnn_dailymail32k/targets/accuracy = 0.5484919, metrics-summarize_cnn_dailymail32k/targets/accuracy_per_sequence = 0.0, metrics-summarize_cnn_dailymail32k/targets/accuracy_top5 = 0.7531322, metrics-summarize_cnn_dailymail32k/targets/approx_bleu_score = 0.23455855, metrics-summarize_cnn_dailymail32k/targets/neg_log_perplexity = -2.6244667, metrics-summarize_cnn_dailymail32k/targets/rouge_2_fscore = 0.31604615, metrics-summarize_cnn_dailymail32k/targets/rouge_L_fscore = 0.4611887```

**Comment by adabghi** [comment]
Anything new on the subject ? I have the same problem of an output with a sequence of a repeated word ..

**Comment by domyounglee** [comment]
I think there's no need to set the "prepend_inputs_masked_attention" to True in summarization task. 
It just literally prepend the encoder inputs to the decoder inputs with a single token between. 
you can use it if you want to use the transformer in Language Model.   
You can check the hyperparameter and  the comment in 
/tensor2tensor/layers/common_hparams.py
 ` " # prepend_inputs_masked_attention"
      #     replace "targets" in preprocessing with
      #     tf.concat([inputs, [0], targets], axis=1)
      #     i.e. we prepend the inputs to the targets with a single
      #     padding token in between.  Use masked self-attention on the
      #     entire resulting sequence.  During training, we compute losses on
      #     the combined sequence.  During eval, we compute the metrics
      #     on only the targets portion.`
